template = ""
rev_id = 8
template_sha = "6ead0c8811e460a0145949f88b0d66e31b788c4a"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "nb"
__UND2C_TRG__ = "se"
__UNDEFINED_SOURCE__ = "Norwegian Bokmål"
__UNDEFINED_TARGET__ = "North Sámi"
__UND_SRC__ = "nob"
__UND_TRG__ = "sme"
