template = ""
rev_id = 7
template_sha = "94893e7a5cd0adce3abaa3e278710450dd114995"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "nb"
__UND2C_TRG__ = "se"
__UNDEFINED_SOURCE__ = "Norwegian Bokmål"
__UNDEFINED_TARGET__ = "North Sámi"
__UND_SRC__ = "nob"
__UND_TRG__ = "sme"
