# This template merge config file lists:
#
# - name: name of template stuff
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
# - ignored: never used in merging, only when populating new repos

name = "Dictionary Template"
patterns = ["nob", "nb", "Norwegian Bokmål", "sme", "se", "North Sámi", "CC-BY-4.0"]
rev_id = 4
required = [".gitignore",
            ".github/workflows/docsygen.yml",
            "docs/_config.yml",
            "docs/_includes/toc.html",
            "docs/_layouts/default.html",
            "docs/assets/css/style.scss"]

optional = ["README.md",
            "docs/index.md"]

ignored  = ["LICENSE",
            ".gut/delta.toml"]
