name: Docs
on: [push]
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: dict

# Mermaid processing starts here:
      - name: get list of files
        id: getfile
        run: |
          echo "::set-output name=files::$(find dict/docs -name '*.md' | xargs)"

      - name: print list of files for debugging
        run: |
          echo ${{ steps.getfile.outputs.files }}

# The actual Mermaid compilation
      - name: compile mermaid
        uses: divvun/compile-mermaid-markdown-action@main
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'dict/docs/mermaid-svgs'
        env:
          HIDE_CODEBLOCKS: 1
# The next one must be declared, with an empty value, for paths to work for us:
          ABSOLUTE_IMAGE_LINKS:
          OUTPUT_FILE_TYPE: "svg"

      - name: list generated svg fils
        run: |
          cd dict && ls -l docs/mermaid-svgs
# Mermaid processing ends here

      - name: deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dict/docs/
          enable_jekyll: true
