name: Docs
on:
  push:
    branches:
      - main
      - docsgen-upgrade

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs:
    uses: giellalt/.github/.github/workflows/docs.yml@main
